language: "perl"

os:
  - linux

dist:
  - trusty

perl:
  - "5.14"

env:
  - COVERALLS=true  DB=mysql

sudo: false

addons:
    apt:
        packages:
        - unzip

before_install:
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
    - git clone -b release-1-6-924 --depth 1 https://github.com/bioperl/bioperl-live.git

install:
    - cpanm -v --installdeps --with-recommends --notest --cpanfile ./cpanfile .  
    - cpanm -v --installdeps --notest .
    - cpanm -n Devel::Cover::Report::Coveralls
    - cp travisci/MultiTestDB.conf.travisci  modules/t/MultiTestDB.conf

script: "./travisci/harness.sh"

notifications:
  email:
    on_success: always
    on_failure: always
